modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Wulian233/AwesomeSheepSwell/issues"
license = "GPL3"

[[mods]]
modId = "awesomesheepswell"
version = "${version}"
displayName = "Awesome Sheep Swell"
displayURL = "https://github.com/Wulian233/AwesomeSheepSwell/"
authors = "Wulian233"
credits = "suppergerrie2"
description = '''
The wool thickens as the sheep eats grass, and you'll get more wool when sheared!
'''
logoFile = "icon.png"

[[mixins]]
config = "awesomesheepswell.mixins.json"

[[dependencies.awesomesheepswell]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.awesomesheepswell]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.awesomesheepswell]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"